"""Generated measured hardware contract for Berkeley Humanoid Lite.

Generated by bhl_hardware_limit_tool.py.
Do not hand-edit numeric limits; regenerate from authoritative_hardware_contract.yaml.
"""

from __future__ import annotations

ACTIONABLE_JOINTS_V1_2_3 = [
    'leg_left_hip_roll_joint',
    'leg_left_hip_yaw_joint',
    'leg_left_hip_pitch_joint',
    'leg_left_knee_pitch_joint',
    'leg_left_ankle_pitch_joint',
    'leg_left_ankle_roll_joint',
    'leg_right_hip_roll_joint',
    'leg_right_hip_yaw_joint',
    'leg_right_hip_pitch_joint',
    'leg_right_knee_pitch_joint',
    'leg_right_ankle_pitch_joint',
    'leg_right_ankle_roll_joint',
]

TRAINING_DEFAULT_RAD = [
    0,
    0,
    -0.1,
    0.4,
    -0.3,
    0,
    0,
    0,
    -0.1,
    0.4,
    -0.3,
    0,
]

HARDWARE_LOWER_LIMIT_RAD = [
    -0.694893296912,
    -0.0889708856974,
    -1.92207792722,
    0.134990309334,
    -0.809941856004,
    -0.513883563942,
    -0.874369049095,
    -0.0567572891518,
    -1.99110706268,
    0.171805848243,
    -0.845223414125,
    -0.443320447699,
]

HARDWARE_UPPER_LIMIT_RAD = [
    0.780796221034,
    0.644271930912,
    0.681087469821,
    2.23501000795,
    0.710233104791,
    0.912718568792,
    0.642737950124,
    0.701029220064,
    0.546097160487,
    2.2411459311,
    0.819145740731,
    1.06151470522,
]


def map_bounded_action_scalar(action: float, default: float, lower: float, upper: float) -> float:
    """Map normalized action [-1, 1] asymmetrically around the training default."""
    a = max(-1.0, min(1.0, float(action)))
    if a >= 0.0:
        return default + a * (upper - default)
    return default + (-a) * (lower - default)


def validate_contract() -> None:
    n = len(ACTIONABLE_JOINTS_V1_2_3)
    if not (
        len(TRAINING_DEFAULT_RAD)
        == len(HARDWARE_LOWER_LIMIT_RAD)
        == len(HARDWARE_UPPER_LIMIT_RAD)
        == n
    ):
        raise ValueError("hardware-contract arrays must have identical lengths")
    for name, default, lower, upper in zip(
        ACTIONABLE_JOINTS_V1_2_3,
        TRAINING_DEFAULT_RAD,
        HARDWARE_LOWER_LIMIT_RAD,
        HARDWARE_UPPER_LIMIT_RAD,
    ):
        if not lower <= default <= upper:
            raise ValueError(
                f"Training default for {name} ({default}) is outside [{lower}, {upper}]"
            )


validate_contract()
